EduHome/Areas/Admin/Controllers/NoticeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using EduHome.DAL;
using EduHome.Models;
using EduHome.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static EduHome.Extensions.Extension;

namespace EduHome.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class NoticeController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _env;
        public NoticeController(AppDbContext db, IWebHostEnvironment env)
        {
            _db = db;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            HomeVM homeVM = new HomeVM()
            {
                VideoTour = await _db.VideoTours.FirstOrDefaultAsync(),
                NoticeBoards = await _db.NoticeBoards.ToListAsync()
            };
            return View(homeVM);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NoticeBoard notice)
        {
            await _db.NoticeBoards.AddAsync(notice);

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return NotFound();
            bool isExist = _db.NoticeBoards.Any(c => c.Id == id);
            if (!isExist) return NotFound();
            NoticeBoard notice = await _db.NoticeBoards.Where(c => c.Id == id).FirstOrDefaultAsync();
            return View(notice);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, NoticeBoard notice)
        {
            NoticeBoard noticeBoard = await _db.NoticeBoards.Where(c => c.Id == id).FirstOrDefaultAsync();

            noticeBoard.NoticeDate = DateTime.UtcNow;
            noticeBoard.Descriptioon = notice.Descriptioon;

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> VideoUpdate(int? id)
        {
            if (id == null) return NotFound();
            bool isExist = _db.VideoTours.Any(c => c.Id == id);
            if (!isExist) return NotFound();
            VideoTour video = await _db.VideoTours.Where(c => c.Id == id).FirstOrDefaultAsync();
            return View(video);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> VideoUpdate(int id, VideoTour video)
        {

            VideoTour videoTour = await _db.VideoTours.Where(c => c.Id == id).FirstOrDefaultAsync();
            if (!ModelState.IsValid) return View(videoTour);

            if (video.Photo != null)
            {
                if (!video.Photo.IsImage())
                {
                    ModelState.AddModelError("", "Please,add Image file");
                    return View(videoTour);
                }
                if (!video.Photo.MaxSize(500))
                {
                    ModelState.AddModelError("", "Max size of Image should be lower than 500");
                    return View(videoTour);
                }
                string folder = Path.Combine("img", "notice");
                string fileName = await video.Photo.SaveImagesAsync(_env.WebRootPath, folder);
                string path = Path.Combine(_env.WebRootPath, folder, videoTour.Image);
                videoTour.Image = fileName;
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
            }

            videoTour.VideoLink = video.VideoLink;

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            NoticeBoard notice = _db.NoticeBoards.Where(e => e.Id == id).FirstOrDefault();
            return Json(notice);
        }
        public async Task<IActionResult> DeletePost(int id)
        {
            NoticeBoard notice = await _db.NoticeBoards.Where(e => e.Id == id).FirstOrDefaultAsync();
            if (_db.NoticeBoards.Count() > 1)
            {
                _db.NoticeBoards.Remove(notice);
            }
            else
            {
                return NotFound();
            }
            await _db.SaveChangesAsync();
            return Json(notice);
        }
    }
}

EduHome/Areas/Admin/Views/Notice/Create.cshtml
@model NoticeBoard
@{
    ViewData["Title"] = "Create Notice";
}

<div class="container">
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <form class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                                <div class="form-group">
                                    <label asp-for="Descriptioon">Main Description</label>
                                    <input asp-for="Descriptioon" class="form-control" placeholder="Main Description">
                                    <span class="text-danger" asp-validation-for="Descriptioon"></span>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <a asp-area="Admin" asp-controller="Notice" asp-action="Index" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

EduHome/Areas/Admin/Views/Notice/Index.cshtml
@model HomeVM
@{
    ViewData["Title"] = "Notice";
    int count = 1;
    string url = "Notice";
}
<div class="modal-box">
    <div class="inner-box col-4">
        <div class="modal-img-box">
            <img class=" img-fluid inner-img" src="" />
        </div>
        <div class="modal-body text-uppercase"></div>
        <div class="modal-btn">
            <button class="m-2 btn btn-md btn-danger modal-delete">Delete</button>
            <button class="m-2 btn btn-md btn-primary modal-back">Go Back</button>
        </div>
    </div>
</div>
<div class="row">
    <table class="table table-hover">
        <thead>
            <tr class="text-right">
                <th scope="col"><a class="btn btn-md btn-success" asp-controller="Notice" asp-action="Create">Create Notice</a></th>
            </tr>
            <tr class="text-center">
                <td scope="col">
                    Video
                </td>
                <td class="td-img" scope="col">
                    <img class="img-fluid" style="width:120px!important;" src="~/img/notice/@Model.VideoTour.Image" alt="Alternate Text" />
                </td>
                <td scope="col">
                    @Model.VideoTour.VideoLink
                </td>
                <td scope="col">
                    <a class="btn btn-sm btn-primary" asp-controller="Notice" asp-action="VideoUpdate" asp-route-id="@Model.VideoTour.Id">Update</a>
                </td>
            </tr>
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Notice Create Date</th>
                <th style="width:30%" scope="col">Description</th>
                <th scope="col">Settings</th>
            </tr>
        </thead>
        <tbody class="body">
            @foreach (NoticeBoard e in Model.NoticeBoards)
            {
                <tr class="text-center">
                    <td>@count</td>
                    <td>@e.NoticeDate.ToString("d, MMMM yyyy")</td>
                    <td>@e.Descriptioon</td>
                    <td>
                        <a class="btn btn-sm btn-primary" asp-controller="Notice" asp-action="Update" asp-route-id="@e.Id">Update</a>
                        <button data-delete="@e.Id" data-url="@url" class="btn btn-sm btn-danger delete">Delete</button>
                    </td>
                </tr>
                count++;
            }
        </tbody>
    </table>
</div>

EduHome/Areas/Admin/Views/Notice/Update.cshtml
@model NoticeBoard
@{
    ViewData["Title"] = "Notice Update";
}

<div class="container">
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="notice-left-wrapper">
                <h3>NOTICE BOARD</h3>
                <div class="notice-left">
                        <div class="single-notice-left mb-23 pb-20">
                            <h4>@Model.NoticeDate.ToString("d, MMMM yyyy")</h4>
                            <p>@Model.Descriptioon</p>
                        </div>
                </div>
            </div>
        </div>
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <form class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                                <div class="form-group">
                                    <label asp-for="Descriptioon">Main Description</label>
                                    <input asp-for="Descriptioon" class="form-control" placeholder="Main Description">
                                    <span class="text-danger" asp-validation-for="Descriptioon"></span>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <a asp-area="Admin" asp-action="Index" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

EduHome/Areas/Admin/Views/Notice/VideoUpdate.cshtml
@model VideoTour
@{
    ViewData["Title"] = "Video Update";
}

<div class="container">
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="notice-right-wrapper mb-25 pb-25">
                <h3>TAKE A VIDEO TOUR</h3>
                <div style="background-image: url(/img/notice/@Model.Image);" class="notice-video">
                    <div class="video-icon video-hover">
                        <a class="video-popup" href="@Model.VideoLink">
                            <i class="zmdi zmdi-play"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <form class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                                <div class="form-group">
                                    <div class="form-group">
                                        <label asp-for="Photo" class="form-label">Select Image</label>
                                        <input asp-for="Photo" class="form-control" accept="image/*" type="file">
                                        <span class="text-danger" asp-validation-for="Photo"></span>
                                    </div>
                                    <label asp-for="VideoLink">Main Description</label>
                                    <input asp-for="VideoLink" class="form-control" placeholder="Main Description">
                                    <span class="text-danger" asp-validation-for="VideoLink"></span>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <a asp-area="Admin" asp-controller="Notice" asp-action="Index" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}